networks:
  common-net:
    external: true


services:
  node:
    container_name: ${PROJECT_NAME}-node
    build:
      args:
        - PUSHER_APP_KEY=${PUSHER_APP_KEY}
        - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
        - PUSHER_APP_HOST=${PUSHER_APP_HOST}
    env_file:
      - .envs/node.env

  app:
    container_name: ${PROJECT_NAME}-app
    env_file:
      - .envs/php-ini.env
      - .envs/php-fpm.env
      - .envs/app.env

  web:
    container_name: ${PROJECT_NAME}-web
    env_file:
      - .envs/web.env
    ports:
      - ${HTTP_PUBLISH_PORT}:8080
      - ${HTTPS_PUBLISH_PORT}:8443